# ###########################################################################
#                          Combat Utilities                                 #
#                                                                           #
# Made by: Adolf Hustler                                                    #
# Bug Reports: https://github.com/adolfhustler/CombatUtils/issues           #
# Source Code: https://github.com/adolfhustler/CombatUtils                  #
#                                                                           #
# ###########################################################################

# General Combat Settings
general:
  # Default combat timeout in seconds
  combat-timeout: 15 # Time (in seconds) before players are no longer in combat
  # Should PvP status changes be logged in the console?
  log-pvp-changes: true # Set to 'true' to log PvP status changes to the console

# Grace period a player has after joining the server/teleporting where they are immune to PvP
grace-period:
  enabled: true
  # How long the grace period should last
  seconds: 10

# Player Messages
messages:
  # Message when the player tries to attack someone with PvP disabled
  pvp-disabled-victim: '&cYou cannot attack this player because they have PvP disabled.'
  # Message when the player tries to attack someone when you have PvP disabled
  pvp-disabled-attacker: '&cYou cannot attack this player because you have PvP disabled.'
  # Message when PvP is disabled for the player
  pvp-disabled-self: '&cPvP has been disabled for you!'
  # Message when PvP is enabled for the player
  pvp-enabled-self: '&aPvP has been enabled for you!'
  # Message shown on the action bar during combat
  combat-timer-message: '&cCombat Timer: {time}s' # Format for action bar message during combat
  # Message shown after combat timer ends
  combat-timer-ended: '&aYou are no longer in combat.'
  # Message shown when grace period starts
  grace-period-start: "&aYou have a short grace period of PvP immunity!"
  # Message shown when grace period ends
  grace-period-end: "&cYour PvP grace period has ended!"
  # Message shown when trying to attack a player during their grace period
  grace-period-attack: "&cYou cannot attack players during their grace period!"
  # Message shown when trying to attack a player when you are in a grace period
  grace-period-attack-self: "&cYou cannot attack players when you are in a grace period!"
  # Message shown on the action bar during grace period
  grace-timer-message: "&aGrace Timer: {time}s"

# Permissions
permissions:
  # Permission to toggle PvP for a player
  toggle-pvp: combatutils.toggle # Permission to allow toggling of PvP

# Combat Utilities
combat-utils:
  # Should players who disconnect during combat get punished?
  punish-on-quit: true # If true, players are killed upon quitting during combat

#List of dead players
dead-players: {}

# Optional Custom Death Messages
custom-death-messages:
  # Message shown when a player disconnects during combat
  disconnect-death-message: '&c{player} was killed for disconnecting during combat!'


# Notes:
# 1. You must reload the plugin or restart the server after making changes to this config for them to take effect.
# 2. Use the command '/combatutilsreload' to reload the plugin configuration without restarting the server.
# 3. You can adjust the combat timeout and other settings here to fit your server's needs.
